authors:
  olivierdepin:
    name: Olivier DEPIN
    description: AI Strategy consultant
    avatar: https://avatars.githubusercontent.com/u/223860636
    url: https://linkedin.com/in/olivier-depin-1121815